//New comment
PUT http://localhost:3001/api/post/comment/@UserTest/61fd76211689fb7ea7374c94
Content-Type: application/json

{
    "userComment": "@UserTest",
    "comment": "new comment3",
    "media": null
}

###

//New Like
PUT http://localhost:3001/api/post/like/@UserTest/620bd3fa76de4b85d54e84b0
Content-Type: application/json

{
    "userLiked": "@UserTest"
}